# Generated by Django 4.1.2 on 2022-10-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('multiplyValue', models.IntegerField(default='1')),
                ('kcal', models.FloatField()),
                ('carbs', models.FloatField(blank=True, default='0')),
                ('protein', models.FloatField(blank=True, default='0')),
                ('fat', models.FloatField(blank=True, default='0')),
                ('fiber', models.FloatField(blank=True, default='0')),
                ('saturated_fat', models.FloatField(blank=True, default='0')),
                ('cholesterol', models.FloatField(blank=True, default='0')),
                ('sodium', models.FloatField(blank=True, default='0')),
                ('sugar', models.FloatField(blank=True, default='0')),
                ('potassium', models.FloatField(blank=True, default='0')),
                ('iron', models.FloatField(blank=True, default='0')),
                ('calcium', models.FloatField(blank=True, default='0')),
                ('magnesium', models.FloatField(blank=True, default='0')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredientunit'),
        ),
    ]
