# Generated by Django 4.1.2 on 2022-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='en_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pl_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredientunit',
            name='en_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredientunit',
            name='pl_name',
            field=models.CharField(max_length=120),
        ),
    ]
