# Generated by Django 4.1.2 on 2022-12-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_biceps_json_userprofile_calves_json_and_more'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_category_name', models.CharField(blank=True, max_length=100)),
                ('en_category_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ingredient categories',
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='magnesium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='multiplyValue',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_grams',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_ml',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='multiplier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='cholesterol',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='kcal',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='meal',
            name='potassium',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='saturated_fat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_grams',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_ml',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='sodium',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='sugar',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pl_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='meals.ingredientunit'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MealTemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('ingredient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50)),
                ('kcal', models.FloatField(blank=True, default=None, null=True)),
                ('carbs', models.FloatField(blank=True, default=None, null=True)),
                ('protein', models.FloatField(blank=True, default=None, null=True)),
                ('fat', models.FloatField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('meal_elements', models.ManyToManyField(default='', to='meals.mealtemplateelement')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='meals.ingredientcategory'),
        ),
    ]
