# Generated by Django 4.1.2 on 2022-10-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_ingredients_meal_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient'),
        ),
    ]
