# Generated by Django 4.1.2 on 2022-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_ingredient_en_name_alter_ingredient_pl_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='en_name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pl_name',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
