# Generated by Django 4.1.2 on 2022-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_ingredients_meal_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='magnesium',
        ),
    ]
