# Generated by Django 4.1.2 on 2022-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_ingredient_calcium_remove_ingredient_iron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='en_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='multiplyValue',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
