# Generated by Django 4.1.2 on 2022-10-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_ingredient_en_name_alter_ingredient_kcal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='multiplyValue',
        ),
    ]
