# Generated by Django 4.1.2 on 2022-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_remove_ingredient_multiplyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='serving_grams',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='en_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pl_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
