# Generated by Django 4.1.2 on 2022-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_ingredient_sodium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=5, default='0', max_digits=7),
        ),
    ]
