# Generated by Django 4.1.2 on 2022-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_ingredient_carbs_alter_ingredient_cholesterol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cholesterol',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='potassium',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fat',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='serving_grams',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(blank=True, default='0'),
        ),
    ]
