# Generated by Django 4.1.2 on 2022-10-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_ingredientcategory_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient Categories'},
        ),
    ]
