# Generated by Django 4.1.2 on 2022-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient categories'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_ml',
            field=models.FloatField(blank=True, default='0'),
        ),
    ]
