# Generated by Django 4.1.2 on 2022-10-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_alter_ingredientcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='meals.ingredientcategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cholesterol',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='potassium',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fat',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='serving_grams',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='serving_ml',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
