# Generated by Django 4.1.2 on 2022-10-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_alter_ingredient_cholesterol_alter_ingredient_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
