# Generated by Django 4.1.2 on 2022-10-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_alter_ingredient_carbs_alter_ingredient_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='multiplier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
