# Generated by Django 4.1.2 on 2022-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_ingredientcategory_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='multiplier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
