# Generated by Django 4.1.2 on 2022-10-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_meal_carbs_meal_cholesterol_meal_fat_meal_fiber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
