# Generated by Django 4.1.2 on 2022-10-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0024_alter_meal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
