# Generated by Django 4.1.2 on 2022-11-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meals', '0026_alter_meal_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('ingredient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.FloatField(default=None)),
                ('carbs', models.FloatField(blank=True, default=None, null=True)),
                ('protein', models.FloatField(blank=True, default=None, null=True)),
                ('fat', models.FloatField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('meal_elements', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meals.mealtemplateelement')),
            ],
        ),
    ]
