# Generated by Django 4.1.2 on 2022-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0027_mealtemplateelement_mealtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtemplate',
            name='meal_elements',
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='meal_elements',
            field=models.ManyToManyField(default='', to='meals.mealtemplateelement'),
        ),
    ]
