# Generated by Django 4.1.2 on 2022-11-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0028_remove_mealtemplate_meal_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='meal_name',
            field=models.CharField(default='asdasas', max_length=50),
            preserve_default=False,
        ),
    ]
