# Generated by Django 4.1.2 on 2022-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0029_mealtemplate_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtemplate',
            name='kcal',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
