# Generated by Django 4.1.2 on 2022-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0030_alter_mealtemplate_kcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtemplate',
            name='kcal',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
