# Generated by Django 4.1.2 on 2022-12-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0031_alter_mealtemplate_kcal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sugar',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='meals.ingredientunit'),
        ),
    ]
