# Generated by Django 4.1.2 on 2022-12-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_biceps_json_and_more'),
        ('meals', '0032_remove_ingredient_cholesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
