# Generated by Django 4.1.2 on 2022-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal_kg',
            field=models.CharField(default=models.CharField(max_length=5)),
        ),
    ]
