# Generated by Django 4.1.2 on 2022-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_elo',
            field=models.BooleanField(default=True),
        ),
    ]
