# Generated by Django 4.1.2 on 2022-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_goal_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal_kg',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
