# Generated by Django 4.1.2 on 2022-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_goal_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal_kcal',
            field=models.FloatField(default=0),
        ),
    ]
