# Generated by Django 4.1.2 on 2022-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_goal_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
