# Generated by Django 4.1.2 on 2022-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_activity_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='basal_kcal',
            field=models.FloatField(default=0),
        ),
    ]
