# Generated by Django 4.1.2 on 2022-11-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_basal_kcal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_multiplier',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='basal_kcal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_kcal',
        ),
    ]
