# Generated by Django 4.1.2 on 2022-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_activity_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal_weight',
            field=models.CharField(max_length=15),
        ),
    ]
