# Generated by Django 4.1.2 on 2022-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_biceps_json_userprofile_calves_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal_kg',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
