# Generated by Django 4.1.2 on 2022-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_exercise_en_name_alter_exercise_pl_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='en_name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pl_name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='workout_name',
            field=models.CharField(max_length=105),
        ),
    ]
