# Generated by Django 4.1.2 on 2022-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_met_exercise_min_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='kcal_burnt',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='min_spent',
        ),
        migrations.AddField(
            model_name='workout',
            name='min_spent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
