# Generated by Django 4.1.2 on 2022-11-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_exercise_kcal_burnt_remove_exercise_min_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_time_unit_name', models.CharField(blank=True, max_length=15)),
                ('en_time_unit_name', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Exercise time units',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='time_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='workouts.exercisetimeunit'),
        ),
    ]
