# Generated by Django 4.1.2 on 2022-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_goal_kg'),
        ('workouts', '0011_alter_workout_kcal_burnt_sum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseTemplate',
            new_name='WorkoutTemplate',
        ),
        migrations.RenameModel(
            old_name='ExerciseTemplateElement',
            new_name='WorkoutTemplateElement',
        ),
        migrations.RenameField(
            model_name='workouttemplateelement',
            old_name='quantity',
            new_name='min_spent',
        ),
    ]
