# Generated by Django 4.1.2 on 2022-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_rename_exercisetemplate_workouttemplate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttemplate',
            old_name='kcal_burnt',
            new_name='kcal_burnt_sum',
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='min_spent_sum',
            field=models.FloatField(default=None, null=True),
        ),
    ]
