# Generated by Django 4.1.2 on 2022-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_alter_workouttemplate_workout_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplateelement',
            name='kcal_burnt',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
