# Generated by Django 4.1.2 on 2022-11-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='difficulty',
            new_name='difficulty_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredients_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='ingredients_pl',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_pl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps_en',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps_pl',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
