# Generated by Django 4.1.2 on 2022-11-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_difficulty_recipe_difficulty_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps_en',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_pl',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
