# Generated by Django 4.1.2 on 2022-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_name_en_alter_recipe_name_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name_en',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name_pl',
            field=models.CharField(default='', max_length=155),
        ),
    ]
